// src/config/drawingConstants.js
/**
 * Determines the scaling relationship between the actual drawing content
 * and the padded viewBox generated by the worker for UI display.
 * Example: 0.4 means the content occupies ~40% of the viewBox area.
 * The inverse (1 / 0.4 = 2.5) is the effective margin factor.
 */
export const UI_CONTENT_VIEWBOX_SCALE_FACTOR = 0.4;

// Future: Add other shared constants like default line weights,
// colors, tolerances, PDF metadata defaults, etc.
// export const DEFAULT_PDF_VISIBLE_STROKE_WIDTH = 0.5; // Example
