import React from 'react';

/**
 * Renders a single SVG path
 */
export default function PathElement({ path, stroke, strokeWidth, strokeDasharray, onClick, viewId }) {
  if (!path) return null;

  // Handle different path formats
  const pathData = path.data || (typeof path === 'string' ? path : String(path));

  // Use the already unique path.id generated by the processor
  const uniquePathId = path.id;

  // Use vector-effect to keep stroke width consistent regardless of SVG scaling
  return (
    <path
      id={uniquePathId} // Use the unique path.id
      d={pathData}
      stroke={stroke}
      strokeWidth={strokeWidth}
      fill="none"
      strokeDasharray={strokeDasharray}
      style={{ vectorEffect: 'non-scaling-stroke', cursor: 'pointer' }}
      onClick={() => onClick && onClick(uniquePathId, path)} // Pass unique ID and path object
    />
  );
}